service: tcx-dlp-scanning
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1 # Override in deploy.sh or by passing option to CLI 
  stage: dev # Override in deploy.sh or by passing option to CLI
  memorySize: ${env:MEMORY_SIZE, 1024} # Memory size for Lambda functions
  timeout: ${env:TIMEOUT, 6} # Timeout for Lambda functions
  apiKeys: 
    - firstKey
    #- secondKey # Uncomment to add a second API Key
    # Generate additional keys by listing them here
  apiGateway:
    apiKeySourceType: AUTHORIZER
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    PRESIDIO_ENDPOINT: ${env:PRESIDIO_ENDPOINT, ""} # !!! Must set manually if not using deploy.sh
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  
functions:
  urlTokenAuthorizer:
    handler: dist/urlAuthorizer.auth

  create:
    handler: dist/dlpFunctions/create.create
    events:
      - http:
          path: dlptrigger
          method: post
          cors: true
          private: true
          authorizer:
            name: urlTokenAuthorizer
            resultTtlInSeconds: 0
            identitySource: method.request.querystring.code
            type: request

  get:
    handler: dist/dlpFunctions/get.get
    events:
      - http:
          path: dlptrigger
          method: get
          cors: true
          private: true
          authorizer:
            name: urlTokenAuthorizer
            resultTtlInSeconds: 0
            identitySource: method.request.querystring.code
            type: request

resources:
  Resources:
    DlpStatusItemsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: ${env:DELETION_POLICY, "Retain"} # Must be one of: 'Delete', 'Snapshot' or 'Retain'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: projectId
            AttributeType: S
          -
            AttributeName: resourceId
            AttributeType: S
        KeySchema:
          -
            AttributeName: projectId
            KeyType: HASH
          -
            AttributeName: resourceId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${env:READ_UNITS, 3}
          WriteCapacityUnits: ${env:WRITE_UNITS, 3}
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
