org: mbaghel
app: tcs-aws-devops-dlp
service: tcx-dlp-scanning
frameworkVersion: '2.28.6'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    PRESIDIO_ENDPOINT: ${param:PRESIDIO_ENDPOINT}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
  
functions:
  create:
    handler: dlpFunctions/create.create
    events:
      - http:
          path: dlptrigger
          method: post
          cors: true
          # private: true

  get:
    handler: dlpFunctions/get.get
    events:
      - http:
          path: dlptrigger
          method: get
          cors: true
          # private: true

resources:
  Resources:
    DlpStatusItemsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: projectId
            AttributeType: S
          -
            AttributeName: resourceId
            AttributeType: S
        KeySchema:
          -
            AttributeName: projectId
            KeyType: HASH
          -
            AttributeName: resourceId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
